In [30]:
import pandas as pd
import numpy as np

In [31]:
dados = 'https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv'

df = pd.read_csv(dados, encoding="latin1", sep= ';')
df

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37583,159,3,2026,2026m03,35,4,Cachoeiras de Macacu,3300803,Interior,3,...,5.0,0.0,26,1,0,0,0,0,156,2
37584,165,3,2026,2026m03,33,5,Mangaratiba,3302601,Interior,1,...,13.0,0.0,33,1,0,0,0,0,240,2
37585,166,3,2026,2026m03,33,5,Angra dos Reis,3300100,Interior,2,...,14.0,1.0,91,10,0,0,0,0,744,2
37586,167,3,2026,2026m03,43,5,Paraty,3303807,Interior,0,...,7.0,0.0,25,1,0,0,0,0,259,2
37587,168,3,2026,2026m03,28,5,Rio Claro,3304409,Interior,0,...,1.0,0.0,8,0,0,0,0,0,52,2

In [32]:
array_roubo = df['roubo_veiculo']
array_furto = df['furto_veiculo']
array_rec = df['recuperacao_veiculo']

array_furto = np.array(df['furto_veiculo'])
array_roubo = np.array(df['roubo_veiculo'])
array_rec = np.array(df['recuperacao_veiculo'])

KeyError: 'furto_veiculo'

In [ ]:
#força de correlação entre furto e roubo de veiculos
#atividade 2
matriz_cov_furto_roubo = np.cov(array_furto, array_roubo)
matriz_cov_furto_roubo= matriz_cov_furto_roubo[0,1]

r1=np.corrcoef(array_furto, array_roubo)
correla_furto_roubo = r1[0,1]

In [ ]:
df.describe()

,cisp,mes,ano,aisp,risp,mcirc,hom_doloso,lesao_corp_morte,latrocinio,cvli,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
count,37588.000000,37588.000000,37588.000000,37588.000000,37588.000000,3.758800e+04,37588.000000,37588.000000,37588.000000,37588.000000,...,32942.000000,32942.000000,37588.000000,37588.000000,37588.000000,37588.000000,37588.000000,37588.000000,37588.000000,37588.000000
mean,81.724513,6.453203,2014.274822,20.152708,3.869932,3.791586e+06,2.916383,0.028227,0.095190,3.039800,...,8.737812,0.643737,41.372938,3.231244,0.360434,0.022906,0.013329,0.002208,445.302011,2.989066
std,48.320601,3.465985,6.677154,11.350589,2.011415,1.740552e+06,4.318591,0.180091,0.365578,4.433564,...,14.763082,1.642005,39.454679,4.167554,0.986363,0.180845,0.130521,0.049155,399.884405,0.103996
min,1.000000,1.000000,2003.000000,1.000000,1.000000,3.300100e+06,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
25%,38.000000,3.000000,2009.000000,10.000000,2.000000,3.302601e+06,0.000000,0.000000,0.000000,0.000000,...,2.000000,0.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,107.000000,3.000000
50%,78.000000,6.000000,2014.000000,20.000000,4.000000,3.304557e+06,1.000000,0.000000,0.000000,1.000000,...,5.000000,0.000000,30.000000,2.000000,0.000000,0.000000,0.000000,0.000000,371.000000,3.000000
75%,125.000000,9.000000,2020.000000,30.000000,6.000000,3.304557e+06,4.000000,0.000000,0.000000,4.000000,...,11.000000,1.000000,56.000000,5.000000,0.000000,0.000000,0.000000,0.000000,665.000000,3.000000
max,168.000000,12.000000,2026.000000,43.000000,7.000000,9.999999e+06,43.000000,6.000000,9.000000,43.000000,...,419.000000,60.000000,370.000000,191.000000,112.000000,10.000000,4.000000,2.000000,3185.000000,3.000000

In [ ]:
df = pd.DataFrame(dados)
print(f"Variância: {np.var(df['nota']):.2f}")
print(f"Desvio Padrão: {np.std(df['nota']):.2f}")
cov = np.cov(df['nota'], df['horas'])[0, 1]
print(f"Covariância: {cov:.2f}")
r = np.corrcoef(df['nota'], df['horas'])[0, 1]
print(f"Pearson r: {r:.4f}")
print("Relação: MUITO FORTE POSITIVA!")

ValueError: DataFrame constructor not properly called!

In [ ]:
import numpy as np
import pandas as pd
dados = {
'aluno': ['Ana','Bruno','Carol','Diego',
'Elisa','Felipe','Gabi','Hugo'],
'nota': [8.5, 6.0, 9.2, 5.5, 7.8, 4.0, 9.0, 6.5],
'horas': [6, 3, 8, 2, 5, 1, 7, 4 ]}

In [ ]:
df = pd.DataFrame(dados)
print(f"Variância: {np.var(df['nota']):.2f}")
print(f"Desvio Padrão: {np.std(df['nota']):.2f}")
cov = np.cov(df['nota'], df['horas'])[0, 1]
print(f"Covariância: {cov:.2f}")
r = np.corrcoef(df['nota'], df['horas'])[0, 1]
print(f"Pearson r: {r:.4f}")
print("Relação: MUITO FORTE POSITIVA!")

Variância: 3.02
Desvio Padrão: 1.74
Covariância: 4.48
Pearson r: 0.9834
Relação: MUITO FORTE POSITIVA!

In [ ]:
# Desvio padrão das notas
desvio = np.std(df['nota'])
print(f"Desvio Padrão: {desvio:.2f}")
# Saída: Desvio Padrão: 1.74
# Interpretando com a média
media = np.mean(df['nota'])
print(f"Média das notas: {media:.2f}")
faixa_inf = media - desvio
faixa_sup = media 
print(f"Faixa típica: {media-desvio:.2f} até {media+desvio:.2f}")
# Saída:
# Média das notas: 7.06
# Faixa típica: 5.32 até 8.80

Desvio Padrão: 1.74
Média das notas: 7.06
Faixa típica: 5.32 até 8.80

In [ ]:
matriz_cov = np.cov(df['nota'], df['horas'])
print(matriz_cov)
# [[3.46  4.48]
#  [4.48  6.00]]
# Extraindo só o valor da covariância
    # [ 0 , 1 ] linhas e colunas 
cov_valor = matriz_cov[0, 1]
print(f"Covariância: {cov_valor:.2f}")
# Saída: Covariância: 4.48
# Forma alternativa com Pandas
print(df[['nota','horas']].cov())
#         nota    horas
# nota   3.456   4.479
# horas  4.479   6.000

[[3.45696429 4.47857143]
 [4.47857143 6.        ]]
Covariância: 4.48
           nota     horas
nota   3.456964  4.478571
horas  4.478571  6.000000

In [ ]:
# Forma 1 — Pandas (mais usada na prática)
corr_pandas = df[['nota','horas']].corr()
print(corr_pandas)
#           nota     horas
# nota   1.0000    0.9749
# horas  0.9749    1.0000
# Forma 2 — NumPy
r = np.corrcoef(df['nota'], df['horas'])
print(f"Pearson r = {r[0,1]:.4f}")
# Saída: Pearson r = 0.9749
# Interpretação:
# r = 0.97 → correlação MUITO FORTE positiva
# Confirma: mais horas de estudo = nota maior!

           nota     horas
nota   1.000000  0.983369
horas  0.983369  1.000000
Pearson r = 0.9834